---
title: "Notas de aula 3"
description: "Fontes do direito internacional público e tratados, p.1"
author:
  - name: Luccas Gissoni
  - affiliation: Universidade Zumbi dos Palmares
  - affiliation_url: https://zumbidospalmares.edu.br/
date: "`r Sys.Date()`"
output: distill::distill_article
bibliography: bibliografia.bib
csl: abnt.csl
---

# Introdução: fontes do direito internacional público

-   1920: **Corte da Haia** (tribunal para resolver litígios entre
    estados sem qualquer limitação geográfica ou temática)

-   Necessidade de se determinar as *fontes* nas quais se poderia buscar
    as *normas internacionais*

-   **Fontes:** tratados, costumes e princípios gerais do direito

-   **Meios auxiliares:** jurisprudência e doutrina

-   Possibilidade do emprego da *equidade*

Nesta e nas próximas aulas trataremos dos **tratados**.

# Perspectiva histórica

-   Prática da celebração de tratados: muito antiga, de natureza
    *costumeira* e assentada sobre os princípios do *pacta sunt
    servanda* e da boa-fé

-   Primeiro registro: tratato de paz celebrado entre Hatusil III, Rei
    dos hititas, e Ramsés II, Faraó do Egito, entre 1280 e 1272 a.C.

-   Século XIX: sem perder a consistência costumeira, os tratados
    ampliam seu acervo normativo com a emergência da *multilateralidade*

-   Também nesse século, ocorre, com o *republicanismo* e o
    *constitucionalismo*, a erosão do protagonismo centrado no chefe de
    Estado

> Resultou induvidoso que essa *fase interna*, a da consulta ao
> parlamento como preliminar de ratificação, impôs ao direito das gentes
> uma importante remissão ao direito doméstico dos Estados
> [@rezek_direito_2024 p. 12].

-   **Convenção de Havana sobre tratados (1928):** primeira formalização
    sobre o tema; texto sumário ainda vigente entre oito países
    latinoamericanos, dentre os quais o Brasil

-   **Convenção de Viena sobre o direito dos tratados (1969):** entrou
    em vigor em 1980, sendo ratificada pelo Brasil em 2009; a Convenção
    formaliza normas preexistentes de caráter costumeiro

# O fenômeno convencional

## Conceito

> Tratado é todo acordo formal concluído entre pessoas jurídicas de
> direito internacional público, e destinado a produzir efeitos
> jurídicos. Na afirmação clássica de Georges Scelle, o tratado
> internacional é em si mesmo um simples *instrumento*; identificamo-lo
> por seu processo de produção e pela *forma* final, não pelo conteúdo.
> Este --- como o da lei ordinária em uma ordem jurídica interna --- é
> variável ao extremo [@rezek_direito_2024 p. 12].

## Terminologia

A terminologia empregada é vasta: *acordo, ajuste, arranjo, ata, ato,
carta, código, compromisso, constituição, contrato, convenção, convênio,
declaração, estatuto, memorando, pacto, protocolo e regulamento* etc.

> Esses termos são de uso livre e aleatório, não obstante certas
> preferências denunciadas pela análise estatística: as mais das vezes,
> por exemplo, carta e constituição vêm a ser os nomes preferidos para
> tratados constitutivos de organizações internacionais, enquanto
> ajuste, arranjo e memorando têm largo trânsito na denominação de
> tratados bilaterais de importância reduzida. Apenas o termo concordata
> possui, em direito das gentes, significação singular: esse nome é
> estritamente reservado ao tratado bilateral em que uma das partes é a
> Santa Sé, e que tem por objeto a organização do culto, a disciplina
> eclesiástica, missões apostólicas, relações entre a Igreja católica
> local e o Estado copactuante [@rezek_direito_2024 p. 13].

Essa liberalidade no usto da terminologia não ocorre com alguns nomes
compostos: por exemplo, *acordo de sede* refere-se necessariamente a um
ajuste entre uma organização internacional e um Estado para instalação
física da sede da organização no território do referido Estado; já
*compromisso arbital* designa um ajuste por meio do qual dois Estados
decidem submeter litígio entre eles à arbitragem internacional.

## Formalidade

Tratado é um acordo *formal* e nisto reside sua principal diferença em
relação ao costume. Ela também implica na *escritura*.

## Atores

As partes de um tratado são *pessoas jurídicas de direito internacional
público*: Estados soberanos e organizações internacionais. Empresas
privadas não tem personalidade jurídica de DIP e portanto tampouco
capacidade para celebrar tratados.

## Efeitos jurídicos

Tratados geram vínculos obrigacionais de natureza jurídica. Para isto, é
necessária a efetiva vontade de criá-los (*animus contrahendi*).

> A produção de efeitos de direito é essencial ao tratado, que não pode
> ser visto senão na sua dupla qualidade de ato jurídico e de norma. O
> acordo formal entre Estados é o ato jurídico que produz a norma, e que
> por produzi-la desencadeia efeitos de direito, gera obrigações e
> prerrogativas, caracteriza enfim, na plenitude de seus dois elementos,
> o tratado internacional [@rezek_direito_2024 p. 13].

Os tratados devem, deste modo, ser distinguidos do acordo em sentido
amplo, ainda que formalizado. Fala-se também no *gentlemen's agreement*,
isto é, o "pacto pessoal *entre estadistas*, fundado sobre a honra, e
condicionado, no tempo, à permanência de seus atores no poder\"
[@rezek_direito_2024 p. 13].

# Crítica

> O MILS, como é seu costume, oferece uma definição formal de tratados.
> Ele geralmente remete o leitor ao Artigo 2(1)(a) da Convenção de Viena
> sobre o Direito dos Tratados de 1969, que define um tratado como 'um
> acordo internacional concluído entre Estados em forma escrita e regido
> pelo direito internacional, seja incorporado em um único instrumento
> legal ou em dois ou mais instrumentos relacionados, e qualquer que
> seja sua designação particular'. 38 Há pouca indicação nesta definição
> abstrata das relações sociais encapsuladas em um tratado. Compare isso
> com as definições oferecidas pelos estudiosos soviéticos Korovin e
> Pashukanis: 'Todo acordo internacional é a expressão de uma ordem
> social estabelecida, com um certo equilíbrio de interesses coletivos';
> 39 'Uma obrigação de tratado não é nada mais do que uma forma especial
> de concretização de relações econômicas e políticas.' 40 Essas
> definições, por meio do uso da realidade extratextual, oferecem maior
> percepção do significado de um tratado do que a definição formal
> oferecida pelo MILS. Elas nos remetem tanto ao fato de uma ordem
> social (capitalista) estabelecida quanto sua concretização como regras econômicas e políticas que incorporam um
> certo equilíbrio de interesses coletivos (de classe). Um tratado é
> alcançado na matriz das regras já existentes do 'jogo do tratado' que
> esclarecem o que é permitido e o que é questionável no curso da
> negociação e adoção de acordos internacionais. Essas regras,
> codificadas no 'tratado de tratados', ou seja, a Convenção de Viena
> sobre o Direito dos Tratados de 1969, favorecem participantes
> poderosos no processo de elaboração de tratados. Primeiro, a Convenção
> de Viena não exige nada mais do que a adesão formal às regras da
> democracia deliberativa. Assim, ela não impede a coerção silenciosa
> dos estados --- um fato que tende a ser ignorado pelo MILS. 41 Em
> outras palavras, como Brilmayer aponta, 'argumentos baseados no
> consentimento são enganosamente simples' como explicação para a
> natureza vinculativa dos acordos. 42 Seu 'poder teórico reside na
> sugestão de que talvez nada realmente precise ser justiﬁcado'. 43 Mas,
> como é evidente para qualquer observador de negociações
> internacionais, 'a barganha frequentemente ocorre em um mundo de
> recursos desiguais e custos de oportunidade'. 44 Ela fornece o solo no
> qual a coerção silenciosa floresce. Segundo, há a questão de quem está
> consentindo: o estado ou as pessoas que o constituem? O MILS não
> aborda essa questão, pois a norma do 'direito à governança
> democrática' não exige que a democracia participativa seja institucionalizada. Nas
> circunstâncias, o tratado frequentemente oculta os interesses de
> certas classes sociais, mesmo quando o MILS finge que incorpora
> compromissos acordados de diferentes 'interesses nacionais'. Embora
> seja reconhecidamente difícil capturar a dimensão de classe dos
> tratados na linguagem do direito internacional quando se trata do
> processo de elaboração de leis, 45 não há razão para que o MILS não
> possa preocupa-se com a exclusão de alguns assuntos de interesse para
> classes subalternas do processo de elaboração de tratados, 46 aborda a
> questão da ausência de democracia substantiva em estados consentidores
> e endossa a ideia de responsabilidade transnacional do estado (um
> assunto ao qual retornaremos mais tarde), a fim de promover a causa de
> grupos marginais e oprimidos. 47 Foi apropriadamente observado que
> 'tratados e instrumentos semelhantes a tratados no final do século XX
> tornaram-se muito importantes para o funcionamento da sociedade
> internacional para permanecer ou se tornarem propriedade de qualquer
> disciplina ou subdisciplina'. 48 Pois não há na era da globalização
> nenhum aspecto das relações internacionais que não seja regulado pelo
> direito internacional dos tratados. Portanto, exige abordagens mais
> sofisticadas para os tratados do que as oferecidas pelo MILS. De
> acordo com Johnston, uma 'mudança substancial no tratamento de
> tratados por parte da disciplina legal deve ser premissa\... com base
> na lógica funcional -- não formal -- . . . '. 49 A visão funcionalista
> que ele propõe 'enfatiza a relevância de considerações inerentes ao
> contexto em que a questão ou problema ocorre, para que as normas
> legais sejam mantidas em equilíbrio com as realidades institucionais e
> políticas'. 50 Também compartilhamos o entendimento de que é: útil
> distinguir três tipos de consentimento, variando com o instrumento e
> as circunstâncias de sua negociação: consentimento para ser
> juridicamente responsável em um tribunal, consentimento para ser
> considerado operacionalmente responsável na arena diplomática e
> consentimento para ser moralmente vinculado aos olhos da opinião
> pública progressista. 51 CMILS entende o último como um chamado para a
> avaliação e reformulação de um tratado à luz de seu impacto em certos
> grupos na vida social, a saber a classe trabalhadora, mulheres,
> camponeses e sem-terra, crianças, povos indígenas e assim por diante.
> O CMILS, no entanto, vai além da abordagem funcionalista para promover
> uma estratégia abrangente que promova os interesses das classes
> subalternas, sem minar totalmente uma abordagem orientada para regras.
> Os seguintes elementos, entre outros, constituem tal estratégia.
> Primeiro, o CMILS pede uma codificação adicional das regras da
> democracia deliberativa. A Convenção de Viena sobre o Direito dos
> Tratados precisa ser alterada para incluir disposições que proíbam o
> uso de todas as formas de coerção (por exemplo, coerção econômica e diplomática) em negociações
> internacionais. 52 A CMILS também, para promover a democracia
> deliberativa, exigiria uma maior representação das classes subalternas
> nas equipes de negociação enviadas pelos estados. Segundo, a CMILS
> gostaria de introduzir uma forma de sistema de avaliação de impacto
> social baseado em pessoas. Em apoio a tal processo, a CMILS exigiria,
> inter alia, que os tratados fossem negociados e ratificados com a
> consulta e consentimento dos representantes eleitos do povo. Embora
> essa ação ainda possa não impedir o consentimento a tratados que não
> sejam do interesse das classes subalternas, ela ajudaria a tornar o
> processo mais transparente e passível de dissidência e mobilização
> política. Terceiro, quando se trata de implementação de tratados, o
> CMILS prescreveria um conjunto de ferramentas legais que ofereceriam
> aos estados dependentes e dominados flexibilidade para implementar
> suas obrigações de uma maneira que salvaguardasse os interesses das
> classes subalternas. Assim, por exemplo, no contexto da OMC, o CMILS
> defenderia uma maior deferência às interpretações nacionais e
> implementação de regras em vez de um modo uniforme insistido pelo
> Órgão de Solução de Controvérsias (DSB) da OMC. Pois o princípio da
> deferência nacional se traduz em maior autonomia para os estados em um
> momento em que está sendo subvertido por uma rede de acordos
> internacionais. 53 Ele permitiria que as classes subalternas
> pressionassem o estado a adotar interpretações que salvaguardassem
> seus interesses. Quarto, o CMILS exigiria o esclarecimento e o
> desenvolvimento de regras de interpretação do direito internacional
> consuetudinário para revelar, e, posteriormente, limitar, a influência
> do poder no exercício interpretativo. Seguindo Wittgenstein, o CMILS
> acredita que, uma vez que o significado de uma palavra reside em seu
> uso na linguagem, não existe tal coisa como
> determinância/indeterminação fora do mundo das práticas sociais.54
> Consequentemente, o que deve ser problematizado são as práticas
> sociais (de classe) e não o conceito abstrato de significado. Tal
> problematização ajudaria a focar nas raízes sociais (de classe) da
> interpretação. Posteriormente, há uma necessidade de desenvolver e
> usar 'normas intersticiais' que reconheçam as raízes sociais (de
> classe) de interpretações conflitantes (como manifestadas, inter alia,
> na resistência a interpretações particulares) e chegar ao fechamento
> após tomar conhecimento de as consequências sociais de ambos. 55 As normas intersticiais podem
> ser legais (princípio da boa-fé) ou morais (equidade na resolução de
> reivindicações conflitantes). 56 Quinto, o CMILS reexaminaria e
> destacaria a doutrina rebus sic stantibus ou mudança material nas
> circunstâncias e a tornaria parte integrante do conceito de um tratado
> equilibrado e justo, embora em sua forma consensual. 57 Isso está em
> contraste com o MILS, que afirma que \"nos tempos modernos, é acordado
> que a regra se aplica apenas nas circunstâncias mais excepcionais,
> caso contrário poderia ser usada como uma desculpa para fugir de todos
> os tipos de obrigações inconvenientes\". 58 Essa visão ignora o fato
> de que estados dependentes e dominados podem apenas recorrer à
> doutrina rebus sic stantibus para abordar o problema de tratados
> injustos. Claro que, na análise final, a invocação da cláusula
> dependeria tanto das consequências sociais de obedecer a uma regra
> quanto da resistência coletiva a ela pelos povos afetados. Neste
> contexto, o direito internacional dos direitos humanos é de relevância
> óbvia, e o CMILS sugere que ele deve ser cada vez mais utilizado para
> dar suporte à invocação da doutrina rebus sic stantibus
> [@chimni_outline_2008 p. 66-70, tradução por IA].
