---
title: "Notas de aula 8"
description: "Organizações internacionais"
author:
  - name: Luccas Gissoni
  - affiliation: Universidade Zumbi dos Palmares
  - affiliation_url: https://zumbidospalmares.edu.br/
date: "`r Sys.Date()`"
output: distill::distill_article
bibliography: dip.bib
csl: abnt.csl
---

# Introdução

As organizações internacionais (OIs) constituem um conjunto heterogêneo de entes, variando tanto em aspectos *quantitativos* — como alcance geográfico, pessoal e orçamento — quanto *qualitativos* — como finalidades e objetivos.

> Seus objetivos variam, com efeito, entre a suprema ambição de uma ONU
> --- manter a paz entre os povos, preservar-lhes a segurança, e
> fomentar, por acréscimo, seu desenvolvimento harmônico --- e o
> modestíssimo desígnio de uma UPU, consistente apenas em ordenar o
> trânsito postal extrafronteiras [@rezek_direito_2024 p. 104].

# Teoria geral

A teoria geral das organizações internacionais parte de certos elementos comuns, como a personalidade jurídica e a estrutura orgânica básica.

## Personalidade jurídica

A personalidade jurídica da organização internacional envolve a
capacidade jurídica, conforme tratado pioneiro que constituiu a
Organização Internacional do Trabalho (OIT) em 1919:

> ::: center
> Artigo 39\
> :::
>
> A Organização Internacional do Trabalho deve ter personalidade
> jurídica, e, precipuamente, capacidade para:\
> a) adquirir bens, móveis e imóveis, e dispor dos mesmos;\
> b) contratar;\
> c) intentar ações [@oit_constituicao_1919].

O elemento mais importante da personalidade jurídica é a competência da
organização para celebrar tratados em seu próprio nome. Daí decorre a
personalidade jurídica como *consequência*:

> Paul Reuter, atento à fase incipiente em que se encontrava a
> formulação de uma teoria geral das organizações internacionais,
> insistia em que a personalidade jurídica de direito das gentes não é a
> fonte da competência da organização, mas seu resultado182. Se os
> pactuantes --- ainda que despreocupados de lavrar um dispositivo do
> gênero do art. 39 da Constituição da OIT --- definem os órgãos da
> entidade projetada, assinalando--lhes competências próprias a revelar
> autonomia em relação à individualidade dos Estados-membros, então, a
> partir da percepção dessa estrutura orgânica, e a partir, sobretudo,
> da análise dessas competências, será possível afirmar que o tratado
> efetivamente deu origem a uma nova personalidade jurídica de direito
> internacional público [@rezek_direito_2024 p. 107]

## Órgãos

Aparentemente todas as OIs são dotadas de ao menos dois órgãos que
parecem indispensáveis à sua estrutura: a assembleia geral e a
secretaria. Um terceiro órgão cumemente encontrado é o conselho
permanente.

### Assembleia geral

Local os todos os Estados-membros tenham voz e voto em condições
igualitárias. Representa o corpo dotado da competência legislativa da
entidade. Ela não é permanente, reunindo-se ordinariamente - em geral
uma vez por ano - e convocada extraordinariamente quando o exigirem as
circunstâncias.

### Secretaria

"Órgão de administração, de funcionamento permanente, integrado por
servidores neutros em relação à política dos Estados-membros ---
particularmente à de seus próprios Estados patriais\"
[@rezek_direito_2024 p. 107]. Há uma tendência a se priorizar o mérito
no recrutamento dos pessoal subalterno neutro, e também de se buscar uma
partilha numérica de postos entre os Estados-membro.

### Conselho permanente

Encontrável sobretudo nas OIs de vocação política, tem funcionamento
ininterrupto e competência executiva [@rezek_direito_2024]. Pode ser
composto por representates de todos os Estados-membros, como na
Organização dos Estados Americanos (OEA), ou de alguns deles, eleitos
pela assembleia geral por prazo certo ou dotados de mandato permanente.
O Conselho de Segurança da Organização das Nações Unidas (ONU) conjuga
exatamente as duas formas.

### Outros órgãos

> Em função do seu alcance e dos seus propósitos, a organização
> internacional pode ter estrutura mais ampla, dispondo de outros
> conselhos --- como, na ONU, o Econômico e Social ---, bem assim de
> órgãos técnicos, de órgãos judiciários --- como a Corte da Haia, no
> quadro da ONU, ou as cortes de Estrasburgo e de Luxemburgo, no quadro
> da União Europeia ---, e até mesmo de órgãos temporários, fadados à
> extinção quando tenham atendido a certa finalidade conjuntural
> [@rezek_direito_2024 p. 108]

## Sede da organização

> Carentes de base territorial, as organizações internacionais precisam
> de que um Estado faculte a instalação física de seus órgãos em algum
> ponto do seu território. Essa franquia pressupõe sempre a celebração
> de um tratado bilateral entre a organização e o Estado, a que se dá o
> nome de *acordo de sede* [@rezek_direito_2024 p. 110].

Não necessariamente a sede da OI se encontra em um Estado-membro, como
no caso da Sociedade nas Nações (SDN), percursora da ONU fundada em
1919, que se instalou em Genebra. Assim, negociou acordo de sede com a
Suíça, um Estado não-membro.

O acordo de sede impõe ao Estado celebrante obrigações relativas aos
privilégios garantidos à OI copactuante e aos representantes de outros
Estados-membros (delegados à assembleia geral, membros de conselho etc.)

> Um pedido israelense de fechamento do escritório da Organização para a
> Libertação da Palestina em Genebra foi rejeitado, em 1978, pelo
> Conselho Federal Suíço, que invocou, a propósito, suas obrigações
> resultantes do acordo de sede firmado com a ONU em 1946. O escritório
> da OLP fora aberto em 1975, a pedido das Nações Unidas, cuja
> Assembleia Geral havia decidido convidar a entidade a participar, com
> o estatuto de observador, de conferências e demais trabalhos
> promovidos pela organização [@rezek_direito_2024 p. 110].

##  Representação, garantias, imunidade

> A organização não goza de privilégios apenas no seu lugar de sede. Ela
> se faz representar tanto no território de Estados-membros quanto no de
> Estados estranhos ao seu quadro. Seus representantes externos são
> integrantes da secretaria --- vale dizer, do quadro de funcionários
> neutros --- e gozam de privilégios semelhantes àqueles do corpo
> diplomático de qualquer soberania representada no exterior187. Por
> igual, suas instalações e bens móveis têm a inviolabilidade usual em
> direito diplomático.\
> Problema distinto deste dos privilégios estabelecidos pelo direito
> diplomático (basicamente a Convenção de Viena de 1961) é o da
> imunidade da própria organização internacional à jurisdição
> brasileira, em feito de natureza trabalhista ou outro. A
> jurisprudência assentada no Supremo Tribunal Federal desde 1989188
> somente diz respeito aos Estados estrangeiros, cuja imunidade, no
> passado, entendia-se resultante de "velha e sólida regra costumeira",
> na ocasião declarada insubsistente. No caso das organizações
> internacionais essa imunidade não resultou essencialmente do costume,
> mas de tratados que a determinam de modo expresso: o próprio tratado
> coletivo institucional, de que o Brasil seja parte, ou um tratado
> bilateral específico.\
> A imunidade da organização, em tais circunstâncias, não pode ser
> ignorada, mesmo no processo de conhecimento, e ainda que a demanda
> resulte de uma relação regida pelo direito material brasileiro
> [@rezek_direito_2024 p. 111].

## Finanças da organização

A receita das OIs resulta sobretudo da *cotização* dos Estados-membros.
Outras receitas são bastante secundárias e às vezes não cobrem nem o
respectivo custo. As cotizações não são paritárias, mas obedecem à
*capacidade contributiva* de cada Estado-membro, levando-se em conta seu
poder econômico relativo.

> Assim, no biênio 2019-2021, os Estados Unidos entraram com 22% da
> receita. A China contribuiu com cerca de 12%, seguindo-se --- com
> arredondamento dos números --- o Japão (8½ %), a Alemanha, a França e
> o Reino Unido (6%), a Itália (5%), o Brasil, o Canadá e a Espanha
> (3%), a Rússia (2,5%) e a Austrália (2%). Com cotas superiores a 1%, a
> Coreia do Sul, o México, os Países Baixos, a Turquia e a Suíça fecham
> a lista dos principais contribuintes. Todos os demais membros da ONU,
> cento e setenta e cinco, contribuem com somas correspondentes a menos
> que 1% da receita total, e trinta e nove deles estancam no piso, que é
> de 0,001% (vinte e cinco mil dólares nos últimos anos), embora a
> modéstia de seus recursos em confronto com os das demais nações
> pudesse justificar, no cálculo exato, uma contribuição ainda menor
> [@rezek_direito_2024 p. 115].

As despesas da OI consistem na folha de pagamento do pessoal da
secretara, custeio e manutenção de instalações imobiliárias e
equipamentos, e muitas vezes também no custeio de programas exteriores
de assistência e financiamento.

> No parecer consultivo de 20 de julho de 1962, solicitado pela
> Assembleia Geral da ONU, a Corte da Haia definiu como despesas da
> organização, a serem custeadas por sua verba orçamentária, as
> resultantes das operações da Força de Urgência das Nações Unidas em
> Suez e no Congo, na década de 1950. Essas operações haviam sido
> determinadas por voto majoritário da Assembleia e do Conselho de
> Segurança, sendo que determinados países membros da organização
> resistiam à ideia de copatrociná-las financeiramente
> [@rezek_direito_2024 p. 115].

## Admissão de novos membros

A admissão de novos membros depende de três aspectos:

- Limites de abertura do tratado institucional;
- Adesão à carta;
- Aceitação pelos Estados-membros (beneplácito).

>  Artigo 4.  
1. A admissão como Membro das Nações Unidas fica aberta a todos os Estados amantes da paz que aceitarem as obrigações contidas na presente Carta e que, a juízo da Organização, estiverem aptos e dispostos a cumprir tais obrigações.  
2. A admissão de qualquer desses Estados como Membros das Nações Unidas será efetuada por decisão da Assembléia Geral, mediante recomendação do Conselho de Segurança [@brasil_decreto_1945].

### Limites de abertura do tratado institucional

Os limites podem ter caráter geográfico: a Carta da OEA está aberta à
adesão dos "Estados americanos"; na Liga Árabe, todo "Estado árabe\"
pode tornar-se membro da Organização.

> Na Carta das Nações Unidas a matéria é disciplinada pelo art. 4º: o
> interessado deve ser um Estado pacífico, que aceite as obrigações
> impostas pela carta, e que se entenda capaz de cumpri-las e disposto a
> fazê-lo. Subordina-se a análise destes últimos pressupostos ao juízo
> da própria organização [@rezek_direito_2024 p. 116].

### Adesão ao tratado institucional

Esta é a condição fundamental de ingresso e também a que casa menos
controvérsia: basta o Estado exprimir sua adesão. Esta deve ser
integral, isto é, feita sem reservas, as quais não foram facultadas aos
pactuantes originários.

### Beneplácito à adesão

É dado pelo órgão competente da entidade. Na SDN, a competência era da
Assembleia, que devia se manifestar por dois terços. "Na União Europeia
(UE) é o Conselho que, sob parecer da Comissão, deve assentir por
unanimidade (\...). O Pacto da Liga Árabe prescreve a submissão do
pedido ao Conselho sem nada adiantar sobre o quorum, permitindo supor
que o veto seja praticável\" [@rezek_direito_2024 p. 116].

> A última década do século XX foi marcada por expressivo número de
> admissões no quadro das Nações Unidas. Eram, de um lado, os últimos
> remanescentes coloniais que acederam à condição de Estados
> independentes e, de outro, as soberanias resultantes de
> desmembramentos ocorridos na Europa [@rezek_direito_2024 p. 116].

## Sanções

> A falta aos deveres resultantes de sua qualidade de membro de uma organização internacional pode trazer ao Estado consequências peculiares, quais sejam as sanções previstas pelo tratado constitutivo e aplicáveis pela própria organização, mediante voto em algum de seus órgãos. Essas assumem, usualmente, duas formas: a suspensão de determinados direitos e a exclusão do quadro [@rezek_direito_2025, p. 317].

### Suspensão da condição de membro da organização

#### Ação preventiva ou coercitiva do Conselho de Segurança

> Artigo 5. O Membro das Nações Unidas, contra o qual for levada a efeito ação preventiva ou coercitiva por parte do Conselho de Segurança, poderá ser suspenso do exercício dos direitos e privilégios de Membro pela Assembléia Geral, mediante recomendação do Conselho de Segurança. O exercício desses direitos e privilégios poderá ser restabelecido pelo conselho de Segurança [@brasil_decreto_1945].

#### Estado em atraso no pagamento de sua cota relativa à receita da organização

>  Artigo 19. O Membro das Nações Unidas que estiver em atraso no pagamento de sua contribuição financeira à Organização não terá voto na Assembléia Geral, se o total de suas contribuições atrasadas igualar ou exceder a soma das contribuições correspondentes aos dois anos anteriores completos. A Assembléia Geral poderá entretanto, permitir que o referido Membro vote, se ficar provado que a falta de pagamento é devida a condições independentes de sua vontade [@brasil_decreto_1945].

<div class="warning">
  <p>⚠️ Para saber mais: Estado em atraso</p>
  <p> > Em 21 de maio de 1968 o Haiti era avisado de que perderia seu direito de voto, nos termos do art. 19, caso permanecesse em atraso no pagamento de sua quota (US$ 22,400). Foi essa a primeira vez em que a ONU se animou a pronunciar tal sorte de advertência. Segundo Reuter, as sanções previstas pelo art. 19 poderiam ter atingido dezesseis Estados membros das Nações Unidas na primavera de 1965. Mas, para tanto, era necessária a difícil “conjunção favorável das forças políticas”24. Uma proposta dos Estados Unidos visando à aplicação do art. 19 à União Soviética, então distante da pontualidade na solução de seus débitos, foi prudentemente retirada em 16 de agosto daquele ano.
<br>
Nos últimos dias de seu mandato, em dezembro de 1991, o secretário-geral Perez de Cuellar revelou que somente 64 dentre os 159 membros da ONU estavam em dia com suas obrigações financeiras. O total de débitos em atraso era de 524 milhões de dólares — dos quais 485 milhões eram então devidos pelos Estados Unidos da América. O problema subsiste nos anos recentes, mas em proporções menos graves. Nos primeiros anos deste novo século o montante das contribuições em mora era da ordem de 222 milhões de dólares [@rezek_direito_2025, p. 318].
  </p>
</div>

### Expulsão da organização

>  Artigo 6. O Membro das Nações Unidas que houver violado persistentemente os Princípios contidos na presente Carta, poderá ser expulso da Organização pela Assembléia Geral mediante recomendação do Conselho de Segurança [@brasil_decreto_1945].

<div class="warning">
  <p>⚠️ Para saber mais: expulsão de Estado</p>
  <p> > Atentando ao sistema pelo qual este último órgão formula suas recomendações, verifica-se que a expulsão, tanto quanto a suspensão prevista no art. 5, não será jamais praticável contra qualquer dos cinco membros permanentes, titulares da prerrogativa do veto. O velho Pacto da SDN não abrigava aberração semelhante. Segundo os termos do seu art. 16, § 4, a exclusão era pronunciada por todos os membros do Conselho, exceto o próprio Estado em causa. Este último sistema é consagrado pela Carta da Liga Árabe. Em ambos os casos, o fato suscetível de provocar a exclusão do Estado-membro é a falta aos compromissos decorrentes da qualidade de membro da organização.
<br>
A única exclusão pronunciada pelo Conselho da SDN foi a da União Soviética, em 1939, após ato de agressão contra a Finlândia. A Carta de Bogotá não se refere à perspectiva da exclusão de membros. Não obstante, em 14 de fevereiro de 1962 a organização expulsou oficialmente do seu quadro a república de Cuba, Estado “incompatível com o sistema interamericano”, dando sequência à resolução da Conferência dos ministros das Relações Exteriores, tomada sob proposta do delegado norte-americano Dean Rusk [@rezek_direito_2025, pp. 318-319].
  </p>
</div>

## Retirada voluntária de Estado-membro

> Dois elementos costumam condicionar a retirada voluntária do Estado-membro no quadro das organizações cujos textos fundamentais preveem a eventualidade da denúncia. Tem-se, em primeiro lugar, o pré-aviso: um lapso de tempo deve mediar entre a manifestação de vontade do Estado retirante e o rompimento efetivo do vínculo jurídico decorrente da sua condição de parte no tratado. O prazo de dois anos, previsto pelo art. 1, § 3, do Pacto da SDN, vale atualmente no sistema da OIT e no da OEA, entendendo esta última como termo inicial a data do recebimento da denúncia pela Secretaria Geral. O segundo requisito costuma ser a atualização de contas (OEA, OIT) [@rezek_direito_2025, p. 19].

A Carta da ONU não prevê a hipótese de retirada.

<div class="warning">
  <p>⚠️ Para saber mais: retirada de Estado</p>
  <p> > A história da Sociedade das Nações registrou a retirada do Brasil em 1926, a do Japão e a da Alemanha em 1933, a da Itália em 1937. Em 21 de janeiro de 1965, em carta endereçada ao secretário-geral das Nações Unidas, o governo da Indonésia participava formalmente seu afastamento da organização. Nada constando na carta sobre semelhante hipótese, o secretário-geral consultava nos dias seguintes numerosas delegações a fim de saber o que deveria ser feito em tais circunstâncias. Iniciativa sem êxito. Do ponto de vista das Nações Unidas, uma situação jurídica inominada e indefinida iria perdurar até 28 de setembro de 1966, data em que os delegados da Indonésia retomaram seus assentos na Assembleia Geral, como se nada houvesse ocorrido.
<br>
A Organização dos Estados Americanos viu deixar seu quadro a república da Bolívia, ressentida após um conflito sobre limites com o Chile. Ela voltaria ao cabo de dois anos de ausência, em 29 de dezembro de 1964. Os Estados Unidos deixaram a OIT em 1977, alegando inconformismo com a politização da entidade. Igual argumento utilizariam em 1984 para deixar a UNESCO. Voltaram depois às duas organizações, em 1980 e em 2003, respectivamente.
  </p>
</div>

# Espécies

@rezek_direito_2025 propõe uma classificalção "experimental e casuística" para as espécies de organização internacional segundo seu **alcance** (universal x regional) e **domínio temático**.

> Entenderíamos como organização de alcance universal toda aquela vocacionada para acolher o maior número possível de Estados, sem restrição de índole geográfica, cultural, econômica ou outra. No tocante ao domínio, também reduziríamos as organizações a duas categorias apenas: as de vocação política — assim vistas aquelas que se consagram sobretudo à preservação da paz e da segurança, embora cuidem, ancilarmente, de outros propósitos — e as de vocação específica: sob esta segunda rubrica lançaríamos as organizações votadas primordialmente a um fim econômico, financeiro, cultural, ou estritamente técnico [@rezek_direito_2025, pp. 320-321].

## Alcance universal, domínio político: a SDN e a ONU

> Primeiro na Sociedade das Nações (1919-1939), depois na Organização das Nações Unidas (1945), somaram-se o alcance universal — a propensão congênita a congregar, um dia, a generalidade dos Estados soberanos, como hoje a ONU de fato congrega — e a finalidade política. No âmbito da ONU, como no de sua antecessora, a cooperação econômica, cultural e científica são propósitos periféricos. Seu objetivo precípuo — frustrado, para a SDN, com a eclosão da segunda grande guerra — é preservar a paz entre as nações, fomentando a solução pacífica de conflitos e proporcionando meios idôneos de segurança coletiva [@rezek_direito_2025, p. 321].

<div class="warning">
  <p>⚠️ Para saber mais: Sociedade das Nações</p>
  <p> > A Sociedade — ou Liga — das Nações foi instituída pelo Tratado de Versalhes em 1919. Teve sede em Genebra (portanto, no território de país não membro, a Suíça). Seus órgãos foram uma Assembleia Geral, uma Secretaria e um Conselho — onde se projetou que haveria quatro membros permanentes, com direito de veto, e quatro temporários, eleitos bienalmente pela Assembleia. Na realidade só três assentos permanentes foram ocupados (França, Grã-Bretanha, Itália), visto que nos Estados Unidos o presidente Woodrow Wilson — um dos principais idealizadores da Sociedade — não conseguiu a aprovação do Senado para ratificar o pacto constitutivo. A SDN ruiu, de fato, em setembro de 1939, quando teve início a segunda grande guerra. As providências relativas à sua extinção formal seriam tomadas algum tempo mais tarde (1946-1947) [@rezek_direito_2025, p. 321].
  </p>
</div>

<div class="warning">
  <p>⚠️ Para saber mais: Organização das Nações Unidas</p>
  <p> > A Organização das Nações Unidas foi planejada nos encontros aliados de Dumbarton Oaks (1944) e de Yalta, este último reunindo, em fevereiro de 1945, o líder soviético Josef Stalin, o primeiro-ministro britânico Winston Churchill e o presidente americano Franklin Roosevelt. Sua carta constitutiva foi negociada na conferência de São Francisco da Califórnia, entre abril e junho de 1945. Três anos mais tarde seus membros eram cinquenta. Hoje esse número é de 193: ali se encontram todas as soberanias formais do mundo contemporâneo, após o ingresso de Timor-Leste e da Suíça em 2002, de Montenegro em 2006 e do Sudão do Sul em 2011. As línguas oficiais da ONU são o árabe, o chinês, o espanhol, o francês, o inglês e o russo, embora apenas o espanhol, o francês e o inglês se empreguem como idiomas de trabalho no cotidiano da organização.
<br>
A Carta de São Francisco descreveu seis órgãos como sendo os principais da ONU, embora um deles — o Conselho de Tutela — devesse encerrar seus trabalhos quando do acesso à independência dos derradeiros territórios sob administração alheia, o que ocorreu em 1994. Os outros são a Assembleia Geral (que realiza sessões anuais, a partir de setembro, e onde todos os Estados-membros têm voz e voto), o Conselho de Segurança, a Secretaria, o Conselho Econômico e Social e a Corte Internacional de Justiça. O Conselho de Segurança tem quinze membros, sendo cinco permanentes (China, Estados Unidos, França, Reino Unido, Rússia) e dez temporários, eleitos pela Assembleia com mandato de dois anos (o Brasil nas últimas décadas foi eleito para os biênios 1998-1999, 2004-2005, 2010-2011 e 2022-2023). No Conselho, as decisões de índole processual são tomadas por nove votos, no mínimo. Quando se cuida de decisões substantivas — as de real importância —, impõe-se que entre os nove votos mínimos favoráveis estejam os cinco dos membros permanentes: isto é o que faz dizer que cada um deles tem poder de veto, porque habilitado a obstruir a decisão por sua singular manifestação negativa. O Conselho Econômico e Social tem cinquenta e quatro membros, todos temporários, elegendo-se a cada ano um grupo de dezoito para um mandato trienal. A Secretaria tem como chefe o secretário-geral das Nações Unidas, eleito pela Assembleia mediante recomendação do Conselho de Segurança, para um mandato de cinco anos, renovável uma só vez, e não podendo dar-se a sucessão por pessoa de igual nacionalidade (foram secretários-gerais da ONU o norueguês Trygve Lie, da fundação a 1953; o sueco Dag Hammarskjöld, de 1953 a 1961; o birmanês U Thant, de 1961 a 1971; o austríaco Kurt Waldheim, de 1971 a 1981; o peruano Javier Perez de Cuellar, de 1981 a 1991; o egípcio Butros Ghali, de 1991 a 1996; o ganense Kofi Annan, de 1997 a 2007). O secretário-geral desde 1º de janeiro de 2007 é o sul-coreano Ban Ki-Moon[^1].
  </p>
</div>

[^1]: Deve-se notar que, desde 2017, o secretário geral da ONU é o português António Guterres. Além disso, para a aprovação das decisões substantivas do Conselho de Segurança não é imprescindível o voto "favorável" dos cinco membros permanentes, bastanto, além dos 9 votos favoráveis, que nenhum destes vote contrariamente à proposta em debate: pode abster-se. No mais, note-se que a língua espanhola não é classificada como língua de trabalho na ONU pela própria Organização; contudo, isto se dá, na prática, e, salvo melhor juízo, exclusivamente, no escritório sede da Comissão Econômica para a América Latina e o Caribe (CEPAL), em Santiago, Chile. Ali, custuma-se exigir conhecimento desse idioma para acessar os posto de trabalho da Comissão [@rezek_direito_2025, pp. 321-322].

## Alcance universal, domínio específico

> Nesta categoria inscrevem-se as chamadas agências especializadas da ONU, que na realidade são organizações internacionais distintas, dotada cada uma delas de personalidade jurídica própria em direito das gentes. Sua gravitação em torno das Nações Unidas resulta de uma circunstância de fato: os Estados-membros são praticamente os mesmos, e não há inconveniente em que, reunidos no foro principal, que é a ONU, ali estabeleçam diretrizes de ação para as organizações especializadas. Exemplos destacados de organizações desta índole são a OIT (Organização Internacional do Trabalho, fundada em 1919 e sediada em Genebra), a UNESCO (Organização das Nações Unidas para a Educação, a Ciência e a Cultura, fundada em 1946 e sediada em Paris), e a FAO (Organização para a Alimentação e a Agricultura, fundada em 1945 e sediada em Roma). Outros exemplos são o Fundo Monetário Internacional (FMI — 1945), a Organização da Aviação Civil Internacional (OACI — 1947), a Organização Mundial de Saúde (OMS — 1948) e o Banco Internacional para a Reconstrução e o Desenvolvimento (BIRD — 1946), também chamado de Banco Mundial [@rezek_direito_2025, p. 323].

<div class="warning">
  <p>⚠️ Para saber mais: Organização Mundial do Comércio</p>
  <p> > A Organização Mundial do Comércio foi instituída por tratado de 15 de dezembro de 1993, concluído no âmbito do GATT[^2], para ser o “quadro institucional comum” das relações comerciais entre seus membros. Seus princípios orientadores são os que desde 1947 vinham prevalecendo no âmbito do GATT: o da não discriminação e o do desarmamento alfandegário. O primeiro se manifesta na cláusula de nação mais favorecida, que povoa desde então os acordos bilaterais de comércio, e que, em linhas muito gerais, garante que cada Estado assegure aos demais o melhor tratamento comercial que já lhe tenha sido possível dar, em iguais circunstâncias, a um determinado Estado com que comercie. Mas é também do princípio da não discriminação que resultam o da reciprocidade (que autoriza a ideia das concessões mediante contrapartida) e o do tratamento nacional (que previne uma política comercial desfavorável ao produto importado). O segundo, o do desarmamento alfandegário, visa a favorecer a liberdade de comércio impedindo que as barreiras aduaneiras sejam um fator de frustração e desaquecimento. É evidente que esses princípios convivem com cláusulas de salvaguarda, que autorizam em caráter excepcional certas medidas restritivas; e ainda com temperamentos próprios para legitimar, por exemplo, o tratamento privilegiado que se concedem os Estados envolvidos em processo regional de integração, qual o Mercosul, ou o tratamento também especial que, sem contrapartida, pode ser concedido por países de maior vitalidade econômica a países em desenvolvimento (aquilo que, já no início dos anos sessenta, Claude Albert Colliard chamava de igualdade ponderada ou desigualdade compensadora).
<br>
A OMC oferece hoje mecanismos de solução de controvérsias comerciais bem mais complexos que os antigos painéis do GATT, que entretanto subsistem, com as alterações normativas de 1994, como uma etapa entre o entendimento direto e o possível exame de recurso pelo Órgão de solução de controvérsias, cuja decisão é obrigatória para as partes [@rezek_direito_2025, pp. 323-324].
  </p>
</div>

[^2]: Acordo Geral sobre Tarifas e Comércio (em inglês, *General Agreement on Tariffs and Trade*, GATT).

## Alcance regional, domínio político

> Nesta categoria encontramos aquelas organizações que retomam, em escala regional, os objetivos da ONU: assim a Organização dos Estados Americanos (OEA — 1951), a Liga dos Estados Árabes (LEA — 1945), a Organização da Unidade Africana (OUA — 1963). Todas têm como vocação principal a manutenção da paz entre seus próprios membros [@rezek_direito_2025, p. 324].

<div class="warning">
  <p>⚠️ Para saber mais: Organização do Tratado do Atlântico Norte</p>
  <p> > Aqui se poderiam ainda contar, outrora, aquelas organizações regionais cuja finalidade política teve também por tônica a segurança, mas que assentaram sobre a premissa da perfeita solidariedade entre seus Estados-membros e se votaram, em última análise, à defesa contra aquilo que lhes parecia um risco exterior potencial: tal o caso da Organização do Tratado do Atlântico Norte (OTAN ou NATO — 1949) e de sua réplica socialista, a Organização do Pacto de Varsóvia (1955). Finda a guerra fria e reformados os regimes políticos do Leste europeu, foi extinto o Pacto de Varsóvia em 1991.
<br>
A OTAN sobreviveu e, perdido seu primitivo propósito, não assumiu formalmente nenhum outro. Esteve mobilizada durante a guerra do Golfo em 1991. Realizou depois manobras militares de rotina. Pretendeu patrocinar, no início de 1992, um empreendimento coletivo de apoio econômico às repúblicas sucessoras da União Soviética. No primeiro semestre de 1999, em campanha encabeçada pelos Estados Unidos e pelo Reino Unido, com o apoio militar de alguns dos seus outros membros, a OTAN bombardeou intensamente a Iugoslávia em nome dos direitos humanos de minorias étnicas locais, destacadamente no Kosovo. A aventura fez mais vítimas civis que militares, muitas delas integrantes das minorias alegadamente protegidas. As instalações atingidas foram, em grande parte, daquelas que as Convenções de Genebra mandam poupar. Terminada a empresa, seus resultados mostraram um mérito mais que duvidoso. Acima de tudo a OTAN chamou a si, sem explicar de onde lhe vinha legitimidade para tanto, uma competência que é das Nações Unidas. Não foi pequena a extensão do desgaste que o episódio representou para a imagem da ONU, para sua credibilidade, para seu futuro [@rezek_direito_2025, p. 324].
  </p>
</div>

## Alcance regional, domínio específico

> Nesta classe figuram as organizações regionais de cooperação e integração econômicas, como a União Europeia (1992) e suas precursoras na Europa comunitária: a Comunidade Europeia do Carvão e do Aço (CECA — 1952) e a Comunidade Europeia da Energia Atômica (CEEA — 1957); a Associação Latino-Americana de Integração (ALADI — 1981), o Acordo de Livre Comércio da América do Norte (NAFTA — 1994) e o Mercosul (1995). Esta é, ainda, a categoria em que se podem classificar instituições como a Organização dos Países Exportadores de Petróleo — a OPEP, criada em 1960 e sediada em Viena [@rezek_direito_2025, p. 324].

<div class="warning">
  <p>⚠️ Para saber mais: Mercado Comum do Sul</p>
  <p> > Com o Protocolo de Ouro Preto, vigente desde 1995, o Mercosul tornou-se uma organização internacional, também regional e de domínio específico. De início, um tratado sem natureza institucional foi firmado em Assunção em 26 de março de 1991, vigendo no mesmo ano. Com ele, Argentina, Brasil, Paraguai e Uruguai instauraram o processo de criação de um mercado comum, ampliados assim o alcance e os objetivos do que fora originalmente um projeto argentino-brasileiro. O Mercosul não foi desde logo dotado de personalidade jurídica própria, isto em função de uma política exemplarmente sóbria com que seus quatro fundadores quiseram evitar todo aparato precoce e todo dispêndio de discutível necessidade. O Protocolo de Brasília, de dezembro de 1991, disciplinou a solução de controvérsias, sem criar qualquer órgão judiciário para o Mercosul: quando as discórdias não se resolvessem por entendimento direto, ou no âmbito deliberativo do próprio grupo, recorrer-se-ia à arbitragem. Nos primeiros dez anos não foi grande o número de controvérsias cuja solução pediu mais que o simples entendimento direto. Não obstante, o Protocolo de Olivos, vigente desde janeiro de 2004, criou um Tribunal Permanente de Revisão: uma instância de recurso das decisões arbitrais ad hoc do Protocolo de Brasília28. O Protocolo de Ouro Preto já havia dado ao Mercosul personalidade jurídica e determinado em definitivo sua estrutura institucional: um conselho, um grupo executivo, algumas comissões especiais, uma secretaria. Nos órgãos colegiados figuram todos os Estados-membros, e o sistema deliberativo reclama unanimidade por via de consenso.
<br>
O Mercosul está em vias de superar a fase da zona de livre comércio (supressão das barreiras alfandegárias em cada país para bens e serviços originários dos demais sócios), tornando-se, em pouco tempo mais, uma perfeita união aduaneira (quando consumada a tarifa externa comum). Seu objetivo vai além, e em algum tempo mais essa organização regional poderá configurar um mercado comum, onde o planejamento da economia seja feito pelo grupo, que conserva seus quatro fundadores — além da Venezuela, admitida em 2012 — como O Mercosul está em vias de superar a fase da zona de livre comércio (supressão das barreiras alfandegárias em cada país para bens e serviços originários dos demais sócios), tornando-se, em pouco tempo mais, uma perfeita união aduaneira (quando consumada a tarifa externa comum). Seu objetivo vai além, e em algum tempo mais essa organização regional poderá configurar um mercado comum, onde o planejamento da economia seja feito pelo grupo, que conserva seus quatro fundadores — além da Venezuela, admitida em 2012 — como membros a título pleno, e tem como associados (com participação diferenciada) o Chile e a Bolívia [@rezek_direito_2025, pp. 325-326].
  </p>
</div>