---
title: "PAP 1.2"
description: |
  Prazo: 23/02
author:
  - name: Luccas Gissoni
    affiliation: Universidade Zumbi dos Palmares
    affiliation_url: https://zumbidospalmares.edu.br/
date: "`r Sys.Date()`"
output: distill::distill_article
bibliography: bibliografia.bib
csl: abnt.csl
---

Às vésperas do fim da Guerra Fria, em meados de 1989, o filósofo e economista político estadunidense Francis Fukuyama publicou o famoso artigo [*The End of History?*](https://www.jstor.org/stable/24027184) [@fukuyama_end_1989] na revista *The National Interest*. Leia no idioma original ou [aqui](resources/fukuyama_fimdahistoria.pdf) o artigo traduzido por inteligência artificial e responda às seguintes perguntas:

1. No seu entendimento, Fukuyama pode ser considerado um pensador filiado à tradição realista ou liberal? Identifique as teses dessa tradição no artigo do autor.

1. Como os argumentos da tradição oposta se contrapõem aos de Fukuyama? Desenvolva essa argumentação rebatendo as teses de Fukuyama.

1. Na sua opinião, os desenvolvimentos da história recente no cenário internacional (emergência da China e dos BRICS, Brexit, eleição de Donald Trump para a presidência dos Estados Unidos, e as guerras na Ucrânia e na Palestina, apenas para citar alguns) confirmam ou descartam a hipótese de Fukuyama? Desenvolva.




